### ISSUE TITLE
Typo in configuration reference? edge > marker > type "array" vs. "arrow"

### ISSUE THREAD

**Issue by ctrueblood-epri** [dash14/v-network-graph-docs#1]
https://github.com/dash14/v-network-graph-docs/blob/85374916f47f9e2a22d150e7b1dbb2b55caa02ed/docs/reference.md#L215

Should `"array"` be `"arrow"`?

**Comment by dash14** [comment]
Hi @ctrueblood-epri,

Thanks a lot for pointing that out.
I've fixed it and deployed it.
